name: CD - Despliegue a Produccion

on:
  push:
    branches: [ production ] 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Render (Simulación)
      run: echo "Despliegue a producción iniciado..."
